[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.hyperfold_engine]
path = "../hyperfold-engine"
version = "0.1.0"
dependency = ""
